"use client";

import React, { useState } from 'react';
import { BrandIdentity } from '@/lib/data';
import { Button } from '@/components/ui/button';
import { ChevronDown, FileJson, ImageIcon, Package, Share2, FileText, Code2, Box, Check, Loader2, Download, Play, Smartphone, Globe } from 'lucide-react';
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuLabel,
    DropdownMenuSeparator,
    DropdownMenuTrigger,
    DropdownMenuGroup
} from '@/components/ui/dropdown-menu';
import { saveAs } from 'file-saver';
import JSZip from 'jszip';
import html2canvas from 'html2canvas';

// Dynamically import the Heavy components effectively if needed, 
// for now we trigger downloads via logic or redirect to 'view' mode which is cleaner.
// Actually, for "Social Media Kit" and "Brand Guidelines", exporting directly from menu 
// without viewing is hard because we need the DOM rendered.
// Strategy: The menu triggers the "PresentationMode" view OR a hidden render-capture process.
// For MVP: We will use the same "Hidden Container" trick from ExportBrandKit for the 'Full Package',
// and for individual items we might just trigger the Full Package or specific parts.

interface UnifiedExportMenuProps {
    brand: BrandIdentity;
    onViewGuidelines?: () => void;
}

export function UnifiedExportMenu({ brand, onViewGuidelines }: UnifiedExportMenuProps) {
    const [isExporting, setIsExporting] = useState(false);
    const [activeExport, setActiveExport] = useState<string | null>(null);

    // HELPER: Download Text File
    const downloadText = (content: string, filename: string) => {
        const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
        saveAs(blob, filename);
    };

    // 1. Tailwind Config
    const exportTailwind = () => {
        const t = brand.theme.tokens;
        const config = `
module.exports = {
  theme: {
    extend: {
      colors: {
        brand: {
          50: '${t.light.bg}',
          500: '${t.light.primary}',
          900: '${t.light.text}',
          // Add more shades generated by your tool
        },
        dark: {
          bg: '${t.dark.bg}',
          surface: '${t.dark.surface}',
        }
      },
      fontFamily: {
        sans: ['${brand.font.name}', 'sans-serif'],
        heading: ['${brand.font.headingName || brand.font.name}', 'sans-serif'],
      }
    }
  }
}
        `;
        downloadText(config.trim(), 'tailwind.config.js');
    };

    // 2. SVG Logo
    const exportSVG = () => {
        const svgElement = document.getElementById('main-logo-svg'); // Ensure we have an ID on the main logo
        if (!svgElement) {
            alert("Could not find logo element to capture. Please enable logo view.");
            return;
        }
        // Basic grab of outerHTML or create a clean SVG string from data
        // For robustness, generating from data is better, but grabbing DOM is easy v1.
        const svgString = svgElement.outerHTML;
        const blob = new Blob([svgString], { type: 'image/svg+xml;charset=utf-8' });
        saveAs(blob, `${brand.name.toLowerCase()}-logo.svg`);
    };

    // 3. React Component
    const exportReact = () => {
        const component = `
import React from 'react';

export const ${brand.name.replace(/\s+/g, '')}Logo = ({ className }: { className?: string }) => (
  <svg viewBox="0 0 100 100" className={className} fill="none" xmlns="http://www.w3.org/2000/svg">
    {/* Shape Path */}
    <path d="${brand.shape}" fill="currentColor" />
  </svg>
);
        `;
        downloadText(component.trim(), `${brand.name.replace(/\s+/g, '')}Logo.tsx`);
    };

    // 4. Animation Export (Lottie + CSS)
    const exportAnimation = async () => {
        try {
            const { generateLogoAnimation, exportAnimationPackage } = await import('@/components/logo-engine/animation/animation-export');
            const { getSelectedLogo } = await import('@/components/logo-engine/renderers/stored-logo-export');

            const selectedLogo = getSelectedLogo(brand);
            if (!selectedLogo) {
                alert('No logo selected. Please generate a logo first.');
                return;
            }

            // Generate animation for 'fade-in' preset
            const animation = generateLogoAnimation(selectedLogo, 'fade-in', 1000);
            const pkg = exportAnimationPackage(animation);

            // Create ZIP with both files
            const zip = new JSZip();
            zip.file('animation.json', pkg.lottieJson);
            zip.file('animation.css', pkg.cssFile);
            zip.file('README.txt', `# ${brand.name} Logo Animation

Lottie Animation: animation.json
- Import into Lottie player libraries (lottie-web, lottie-react, etc.)
- Test at lottiefiles.com

CSS Animation: animation.css
- Copy keyframes into your stylesheet
- Apply .logo-animation class to your logo element

Generated by Glyph`);

            const content = await zip.generateAsync({ type: 'blob' });
            saveAs(content, `${brand.name.toLowerCase().replace(/\s+/g, '-')}-animation.zip`);
        } catch (e) {
            console.error('Animation export failed:', e);
            alert('Animation export failed. Please try again.');
        }
    };

    // 5. Favicon ICO Export
    const exportFaviconICO = async () => {
        try {
            const { generateFaviconICO } = await import('@/components/export/ExportFavicon');
            const icoBlob = await generateFaviconICO(brand);
            saveAs(icoBlob, 'favicon.ico');
        } catch (e) {
            console.error('Favicon ICO export failed:', e);
            alert('Favicon ICO export failed. Please try again.');
        }
    };

    // 6. App Icons Export (iOS + Android)
    const exportAppIcons = async () => {
        try {
            const { generateAppIcons } = await import('@/components/export/ExportFavicon');
            const { ios, android } = await generateAppIcons(brand);

            const zip = new JSZip();
            zip.file('ios-1024x1024.png', ios);
            zip.file('android-512x512.png', android);
            zip.file('README.txt', `# ${brand.name} App Icons

iOS App Icon: ios-1024x1024.png
- 1024x1024 with proper padding
- No transparency (solid background)
- Upload to App Store Connect

Android App Icon: android-512x512.png
- 512x512 adaptive icon foreground
- 15% padding for safe zone
- Use with ic_launcher

Generated by Glyph`);

            const content = await zip.generateAsync({ type: 'blob' });
            saveAs(content, `${brand.name.toLowerCase().replace(/\s+/g, '-')}-app-icons.zip`);
        } catch (e) {
            console.error('App icons export failed:', e);
            alert('App icons export failed. Please try again.');
        }
    };

    const handleItemClick = async (action: string, fn: () => void) => {
        setActiveExport(action);
        setIsExporting(true);
        // Simulate async
        await new Promise(r => setTimeout(r, 800));
        try {
            fn();
        } catch (e) {
            console.error(e);
        }
        setIsExporting(false);
        setActiveExport(null);
    };

    return (
        <DropdownMenu>
            <DropdownMenuTrigger asChild>
                <Button className="bg-white text-stone-900 border border-stone-200 hover:bg-stone-50 shadow-sm gap-2 rounded-full px-6 shadow-xl hover:shadow-2xl transition-all">
                    {isExporting ? <Loader2 className="animate-spin" size={16} /> : <Download size={16} />}
                    Export
                    <ChevronDown size={14} className="opacity-50" />
                </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end" className="w-80 p-2 rounded-2xl shadow-xl border-stone-100 bg-white/95 backdrop-blur-xl">
                <DropdownMenuLabel className="px-3 py-2 text-xs font-mono text-stone-400 uppercase tracking-widest">
                    Assets & Config
                </DropdownMenuLabel>

                <DropdownMenuGroup className="space-y-1">
                    {/* Tailwind */}
                    <DropdownMenuItem
                        onClick={() => handleItemClick('tailwind', exportTailwind)}
                        className="flex items-start gap-4 p-3 rounded-xl focus:bg-stone-50 cursor-pointer"
                    >
                        <div className="p-2 bg-stone-100 rounded-lg text-stone-600">
                            <SwitchIcon active={activeExport === 'tailwind'} icon={Code2} />
                        </div>
                        <div>
                            <div className="font-semibold text-stone-900">Tailwind Config</div>
                            <div className="text-xs text-stone-500">CSS variables & tokens</div>
                        </div>
                    </DropdownMenuItem>

                    {/* SVG Logo */}
                    <DropdownMenuItem
                        onClick={() => handleItemClick('svg', exportSVG)}
                        className="flex items-start gap-4 p-3 rounded-xl focus:bg-stone-50 cursor-pointer"
                    >
                        <div className="p-2 bg-stone-100 rounded-lg text-stone-600">
                            <SwitchIcon active={activeExport === 'svg'} icon={ImageIcon} />
                        </div>
                        <div>
                            <div className="font-semibold text-stone-900">SVG Logo</div>
                            <div className="text-xs text-stone-500">Vector format</div>
                        </div>
                    </DropdownMenuItem>

                    {/* Social Media Kit (Scroll/Link) */}
                    <DropdownMenuItem
                        onClick={() => {
                            if (onViewGuidelines) onViewGuidelines();
                        }}
                        className="flex items-start gap-4 p-3 rounded-xl focus:bg-stone-50 cursor-pointer"
                    >
                        <div className="p-2 bg-stone-100 rounded-lg text-stone-600">
                            <SwitchIcon active={false} icon={Share2} />
                        </div>
                        <div>
                            <div className="font-semibold text-stone-900">Social Media Kit</div>
                            <div className="text-xs text-stone-500">Profile pics & banners</div>
                        </div>
                    </DropdownMenuItem>

                    {/* Brand Guidelines */}
                    <DropdownMenuItem
                        onClick={() => {
                            if (onViewGuidelines) onViewGuidelines();
                        }}
                        className="flex items-start gap-4 p-3 rounded-xl focus:bg-stone-50 cursor-pointer"
                    >
                        <div className="p-2 bg-stone-100 rounded-lg text-stone-600">
                            <SwitchIcon active={false} icon={FileText} />
                        </div>
                        <div>
                            <div className="font-semibold text-stone-900">Brand Guidelines</div>
                            <div className="text-xs text-stone-500">PDF-ready Brand Book</div>
                        </div>
                    </DropdownMenuItem>

                    {/* React Component */}
                    <DropdownMenuItem
                        onClick={() => handleItemClick('react', exportReact)}
                        className="flex items-start gap-4 p-3 rounded-xl focus:bg-stone-50 cursor-pointer"
                    >
                        <div className="p-2 bg-stone-100 rounded-lg text-stone-600">
                            <SwitchIcon active={activeExport === 'react'} icon={FileJson} />
                        </div>
                        <div>
                            <div className="font-semibold text-stone-900">React Component</div>
                            <div className="text-xs text-stone-500">Copy-paste ready</div>
                        </div>
                    </DropdownMenuItem>

                    {/* Animation Export */}
                    <DropdownMenuItem
                        onClick={() => handleItemClick('animation', exportAnimation)}
                        className="flex items-start gap-4 p-3 rounded-xl focus:bg-stone-50 cursor-pointer"
                    >
                        <div className="p-2 bg-stone-100 rounded-lg text-stone-600">
                            <SwitchIcon active={activeExport === 'animation'} icon={Play} />
                        </div>
                        <div>
                            <div className="font-semibold text-stone-900">Logo Animation</div>
                            <div className="text-xs text-stone-500">Lottie JSON + CSS keyframes</div>
                        </div>
                    </DropdownMenuItem>

                    {/* Favicon ICO */}
                    <DropdownMenuItem
                        onClick={() => handleItemClick('favicon', exportFaviconICO)}
                        className="flex items-start gap-4 p-3 rounded-xl focus:bg-stone-50 cursor-pointer"
                    >
                        <div className="p-2 bg-stone-100 rounded-lg text-stone-600">
                            <SwitchIcon active={activeExport === 'favicon'} icon={Globe} />
                        </div>
                        <div>
                            <div className="font-semibold text-stone-900">Favicon ICO</div>
                            <div className="text-xs text-stone-500">16, 32, 48px embedded</div>
                        </div>
                    </DropdownMenuItem>

                    {/* App Icons */}
                    <DropdownMenuItem
                        onClick={() => handleItemClick('appicons', exportAppIcons)}
                        className="flex items-start gap-4 p-3 rounded-xl focus:bg-stone-50 cursor-pointer"
                    >
                        <div className="p-2 bg-stone-100 rounded-lg text-stone-600">
                            <SwitchIcon active={activeExport === 'appicons'} icon={Smartphone} />
                        </div>
                        <div>
                            <div className="font-semibold text-stone-900">App Icons</div>
                            <div className="text-xs text-stone-500">iOS 1024px + Android 512px</div>
                        </div>
                    </DropdownMenuItem>
                </DropdownMenuGroup>

                <DropdownMenuSeparator className="my-2 bg-stone-100" />

                {/* Full Package */}
                <DropdownMenuItem className="flex items-start gap-4 p-3 rounded-xl focus:bg-stone-900 focus:text-white group cursor-pointer">
                    <div className="p-2 bg-stone-100 rounded-lg text-stone-900 group-focus:bg-stone-800 group-focus:text-white">
                        <Package size={18} />
                    </div>
                    <div>
                        <div className="font-semibold text-stone-900 group-focus:text-white">Full Package</div>
                        <div className="text-xs text-stone-500 group-focus:text-stone-400">ZIP with all assets</div>
                    </div>
                </DropdownMenuItem>

            </DropdownMenuContent>
        </DropdownMenu>
    );
}

function SwitchIcon({ active, icon: Icon }: { active: boolean, icon: any }) {
    if (active) return <Loader2 size={18} className="animate-spin text-orange-500" />;
    return <Icon size={18} />;
}
