"use client";

import { useState, useCallback } from 'react';
import { Sidebar } from '@/components/generator/Sidebar';
import { Toolbar } from '@/components/generator/Toolbar';
import { LoadingState } from '@/components/generator/LoadingState';
import { WorkbenchBentoGrid } from '@/components/generator/WorkbenchBentoGrid';
import { useBrandGenerator } from '@/hooks/use-brand-generator';
import { Menu, X } from 'lucide-react';

import { GenerationOptions } from '@/components/generator/Sidebar';

export default function GeneratorPage() {
  const brandGenerators = useBrandGenerator();
  const { brand, generateBrand, isGenerating, resetBrand } = brandGenerators;
  const [isDarkMode, setIsDarkMode] = useState(false);
  const [selectedVibe, setSelectedVibe] = useState('minimalist');
  const [viewMode, setViewMode] = useState<'overview' | 'presentation'>('overview');
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);

  const handleGenerate = useCallback((options: GenerationOptions) => {
    setIsSidebarOpen(false); // Close drawer on generate
    generateBrand(options.vibe, options.name, {
      color: options.color,
      shape: options.shape,
      gradient: options.gradient,
      surpriseMe: options.surpriseMe
    });
  }, [generateBrand]);

  const handleExport = (type: string) => {
    if (!brand) return;

    if (type === 'svg') {
      const svgContent = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${brand.shape.viewBox || "0 0 24 24"}">
        <path d="${brand.shape.path}" fill="${brand.theme.tokens.light.primary}" />
      </svg>`;
      const blob = new Blob([svgContent], { type: 'image/svg+xml' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `${brand.name.toLowerCase().replace(/\s+/g, '-')}-logo.svg`;
      link.click();
    } else if (type === 'tailwind') {
      const tokens = brand.theme.tokens;
      const config = `// ${brand.name} - Tailwind CSS Config
// Generated by Glyph

module.exports = {
  theme: {
    extend: {
      colors: {
        light: {
          background: "${tokens.light.bg}",
          foreground: "${tokens.light.text}",
          primary: "${tokens.light.primary}",
          surface: "${tokens.light.surface}",
          muted: "${tokens.light.muted}",
          border: "${tokens.light.border}",
        },
        dark: {
          background: "${tokens.dark.bg}",
          foreground: "${tokens.dark.text}",
          primary: "${tokens.dark.primary}",
          surface: "${tokens.dark.surface}",
          muted: "${tokens.dark.muted}",
          border: "${tokens.dark.border}",
        },
      },
    },
  },
};`;
      navigator.clipboard.writeText(config);
      alert('Tailwind config copied to clipboard!');
    } else if (type === 'react') {
      const componentCode = `// ${brand.name} Logo Component
// Generated by Glyph

interface LogoProps {
  className?: string;
  color?: string;
}

export function ${brand.name.replace(/\s+/g, '')}Logo({ className = "w-8 h-8", color = "${brand.theme.tokens.light.primary}" }: LogoProps) {
  return (
    <svg
      viewBox="${brand.shape.viewBox || "0 0 24 24"}"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
    >
      <path d="${brand.shape.path}" fill={color} />
    </svg>
  );
}
`;
      navigator.clipboard.writeText(componentCode);
      alert('React component copied to clipboard!');
    } else if (type === 'all') {
      alert('Full Package export coming soon!');
    }
  };

  return (
    <div className="flex h-screen w-full bg-stone-50 overflow-hidden font-sans">
      <LoadingState isLoading={isGenerating} />

      {/* Mobile Sidebar Toggle Button */}
      <button
        onClick={() => setIsSidebarOpen(!isSidebarOpen)}
        className="md:hidden fixed top-4 left-4 z-50 p-3 bg-white border border-stone-200 rounded-xl shadow-lg active:scale-95 transition-transform"
        aria-label="Toggle Sidebar"
      >
        {isSidebarOpen ? <X className="w-5 h-5" /> : <Menu className="w-5 h-5" />}
      </button>

      {/* Sidebar Overlay (Mobile) */}
      {isSidebarOpen && (
        <div
          className="md:hidden fixed inset-0 bg-black/40 z-30 backdrop-blur-sm"
          onClick={() => setIsSidebarOpen(false)}
        />
      )}

      {/* Sidebar - Hidden on mobile by default, slide-in drawer when open */}
      <div className={`
        fixed md:relative inset-y-0 left-0 z-40
        transform transition-transform duration-300 ease-out
        ${isSidebarOpen ? 'translate-x-0' : '-translate-x-full md:translate-x-0'}
        w-[90vw] max-w-[420px] md:w-[420px]
      `}>
        <Sidebar
          onGenerate={handleGenerate}
          isGenerating={isGenerating}
          selectedVibe={selectedVibe}
          setSelectedVibe={setSelectedVibe}
        />
      </div>

      {/* Main Content */}
      <main className="flex-1 relative bg-[#FAFAF9] overflow-auto">
        <div
          className="absolute inset-0 opacity-40"
          style={{
            backgroundImage: 'radial-gradient(#A8A29E 1px, transparent 1px)',
            backgroundSize: '24px 24px',
          }}
        />

        {/* Toolbar - Responsive positioning */}
        <div className="absolute top-4 right-4 md:top-6 md:right-8 z-30">
          <Toolbar
            isDark={isDarkMode}
            toggleDark={() => setIsDarkMode(!isDarkMode)}
            onExport={handleExport}
            viewMode={viewMode}
            setViewMode={setViewMode}
            canUndo={brandGenerators.canUndo}
            canRedo={brandGenerators.canRedo}
            onUndo={brandGenerators.undo}
            onRedo={brandGenerators.redo}
            currentHistoryIndex={brandGenerators.historyIndex}
            totalHistory={brandGenerators.historyTotal}
          />
        </div>

        <div className={`relative z-10 transition-all duration-500 w-full min-h-full pt-16 md:pt-20 pb-20 px-2 md:px-0 ${isDarkMode ? 'dark' : ''}`}>
          {brand ? (
            <WorkbenchBentoGrid
              brand={brand}
              isDark={isDarkMode}
              onShuffleLogo={() => generateBrand(selectedVibe, brand.name)}
              viewMode={viewMode}
              setViewMode={setViewMode}
            />
          ) : (
            <div className="h-full flex items-center justify-center">
              <div className="text-center space-y-4 opacity-50 animate-in fade-in duration-700 slide-in-from-bottom-4">
                <div className="w-16 h-16 bg-white border border-stone-200 shadow-[inset_0_1px_0_0_rgba(255,255,255,0.5)] rounded-2xl mx-auto flex items-center justify-center">
                  <span className="text-2xl">✨</span>
                </div>
                <p className="font-mono text-[10px] uppercase tracking-widest text-stone-400 max-w-xs mx-auto">
                  Configure Brand DNA
                </p>
              </div>
            </div>
          )}
        </div>
      </main>
    </div>
  );
}

