import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import { BrandIdentity } from '@/lib/data';
import { generateLogoSVG, generateWordmarkSVG, generateFaviconSVG } from '@/lib/svg-exporter';

export async function exportBrandPackage(brand: BrandIdentity) {
  const zip = new JSZip();
  const folderName = brand.name.toLowerCase().replace(/\s+/g, '-');
  const root = zip.folder(folderName);

  if (!root) {
    console.error("Failed to create zip folder");
    return;
  }

  // 1. ICONS / LOGOS (Clean SVG from shape data)
  const icons = root.folder("icons");
  if (icons) {
    // Primary Logo (Color)
    icons.file("logo-color.svg", generateLogoSVG(brand, 'color'));

    // Monotone Black
    icons.file("logo-black.svg", generateLogoSVG(brand, 'black'));

    // Monotone White (for dark backgrounds)
    icons.file("logo-white.svg", generateLogoSVG(brand, 'white'));

    // Outline variant
    icons.file("logo-outline.svg", generateLogoSVG(brand, 'outline'));

    // Wordmark (logo + brand name)
    icons.file("wordmark-color.svg", generateWordmarkSVG(brand, 'color'));
    icons.file("wordmark-black.svg", generateWordmarkSVG(brand, 'black'));

    // Favicon
    icons.file("favicon.svg", generateFaviconSVG(brand));
  }

  // 2. TOKENS / CODE
  const tokens = root.folder("tokens");
  if (tokens) {
    // A. theme.json
    tokens.file("theme.json", JSON.stringify(brand.theme, null, 2));

    // B. tailwind.config.js
    const tailwindConfig = `/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        brand: {
          50: '${brand.theme.tokens.light.bg}',
          100: '${brand.theme.tokens.light.surface}',
          500: '${brand.theme.tokens.light.primary}',
          900: '${brand.theme.tokens.light.text}',
        }
      },
      fontFamily: {
        sans: ['${brand.font.name}', 'sans-serif'],
      }
    },
  },
}`;
    tokens.file("tailwind.config.js", tailwindConfig);

    // C. css-variables.css
    const cssVars = `:root {
  --brand-primary: ${brand.theme.tokens.light.primary};
  --brand-bg: ${brand.theme.tokens.light.bg};
  --brand-surface: ${brand.theme.tokens.light.surface};
  --brand-text: ${brand.theme.tokens.light.text};
  --font-heading: '${brand.font.name}';
  --font-body: '${brand.font.name}';
}`;
    tokens.file("variables.css", cssVars);
  }

  // 3. README
  const readme = `
# ${brand.name} Brand Identity
Generated by Glyph (https://glyph.software)

## Contents
- /icons: SVG vector logo files (Color, Black, White, Outline, Wordmark, Favicon).
- /tokens: Development tokens for Tailwind CSS and CSS variables.

## Usage
- Use 'logo-color.svg' for standard use.
- Use 'logo-white.svg' for dark backgrounds.
- Use 'wordmark-color.svg' when you need the logo with brand name.
- Use 'favicon.svg' for browser favicons.
- Always maintain clear space around the logo.

## Fonts
Primary Font: ${brand.font.name}
This brand uses Google Fonts. You may need to license them for offline use.
`;
  root.file("README.txt", readme.trim());

  // GENERATE ZIP
  const content = await zip.generateAsync({ type: "blob" });
  saveAs(content, `${folderName}-assets.zip`);
}
