import React from 'react';
import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import { BrandIdentity } from '@/lib/data';
import { renderToStaticMarkup } from 'react-dom/server';
import { LogoComposition } from '@/components/brand/LogoComposition';

export async function exportBrandPackage(brand: BrandIdentity) {
  const zip = new JSZip();
  const folderName = brand.name.toLowerCase().replace(/\s+/g, '-');
  const root = zip.folder(folderName);

  if (!root) {
    console.error("Failed to create zip folder");
    return;
  }

  // 1. ICONS / LOGOS
  const icons = root.folder("icons");
  if (icons) {
    // A. Primary Logo (Color)
    const primarySvg = renderToStaticMarkup(
      <LogoComposition
        brand={brand}
      />
    );
    icons.file("logo-primary.svg", extractSvg(primarySvg));

    // B. Monotone Black (We cheat by making a temp brand with black colors)
    // LogoComposition reads from brand.theme.tokens.light directly.
    // For export, we need to temporarily clone the brand with overridden colors.
    const blackBrand = { ...brand, theme: { ...brand.theme, tokens: { ...brand.theme.tokens, light: { ...brand.theme.tokens.light, primary: '#000000', text: '#000000', accent: '#000000', bg: 'transparent' } } } };
    const blackSvg = renderToStaticMarkup(
      <LogoComposition brand={blackBrand} />
    );
    icons.file("logo-black.svg", extractSvg(blackSvg));

    // C. Monotone White
    const whiteBrand = { ...brand, theme: { ...brand.theme, tokens: { ...brand.theme.tokens, light: { ...brand.theme.tokens.light, primary: '#FFFFFF', text: '#FFFFFF', accent: '#FFFFFF', bg: 'transparent' } } } };
    const whiteSvg = renderToStaticMarkup(
      <LogoComposition brand={whiteBrand} />
    );
    icons.file("logo-white.svg", extractSvg(whiteSvg));
  }

  // 2. TOKENS / CODE
  const tokens = root.folder("tokens");
  if (tokens) {
    // A. theme.json
    tokens.file("theme.json", JSON.stringify(brand.theme, null, 2));

    // B. tailwind.config.js
    const tailwindConfig = `/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        brand: {
          50: '${brand.theme.tokens.light.bg}',
          100: '${brand.theme.tokens.light.surface}',
          500: '${brand.theme.tokens.light.primary}',
          900: '${brand.theme.tokens.light.text}',
        }
      },
      fontFamily: {
        sans: ['${brand.font.name}', 'sans-serif'],
      }
    },
  },
}`;
    tokens.file("tailwind.config.js", tailwindConfig);

    // C. css-variables.css
    const cssVars = `:root {
  --brand-primary: ${brand.theme.tokens.light.primary};
  --brand-bg: ${brand.theme.tokens.light.bg};
  --brand-surface: ${brand.theme.tokens.light.surface};
  --brand-text: ${brand.theme.tokens.light.text};
  --font-heading: '${brand.font.name}';
  --font-body: '${brand.font.name}';
}`;
    tokens.file("variables.css", cssVars);
  }

  // 3. README
  const readme = `
# ${brand.name} Brand Identity
Generated by Glyph (https://glyph.software)

## Contents
- /icons: SVG vector logo files (Primary, Black, White).
- /tokens: Development tokens for Tailwind CSS and CSS variables.

## Usage
- Use 'logo-primary.svg' for white/light backgrounds.
- Use 'logo-white.svg' for dark backgrounds.
- Always maintain clear space around the logo.

## Fonts
Primary Font: ${brand.font.name}
This brand uses Google Fonts. You may need to license them for offline use.
`;
  root.file("README.txt", readme.trim());

  // GENERATE ZIP
  const content = await zip.generateAsync({ type: "blob" });
  saveAs(content, `${folderName}-assets.zip`);
}

// Helper to extract SVG from the React render string (which includes a wrapper div)
function extractSvg(html: string): string {
  const match = html.match(/<svg[\s\S]*?<\/svg>/);
  return match ? match[0] : html;
}
