/**
 * PDF Generator for Brand Books
 * 
 * Uses jspdf + html2canvas to create real PDF downloads.
 */

import { jsPDF } from 'jspdf';
import { BrandIdentity } from './data';

/**
 * Generate a brand book PDF
 */
export async function generateBrandBookPDF(brand: BrandIdentity): Promise<Blob> {
    const colors = brand.theme.tokens.light;
    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const contentWidth = pageWidth - (margin * 2);

    // Helper to add text
    const addText = (text: string, x: number, y: number, options?: {
        fontSize?: number;
        fontStyle?: 'normal' | 'bold';
        color?: string;
        maxWidth?: number;
    }) => {
        const { fontSize = 12, fontStyle = 'normal', color = '#1a1a1a', maxWidth } = options || {};
        doc.setFontSize(fontSize);
        doc.setFont('helvetica', fontStyle);

        // Parse hex color
        const hex = color.replace('#', '');
        const r = parseInt(hex.substring(0, 2), 16);
        const g = parseInt(hex.substring(2, 4), 16);
        const b = parseInt(hex.substring(4, 6), 16);
        doc.setTextColor(r, g, b);

        if (maxWidth) {
            doc.text(text, x, y, { maxWidth });
        } else {
            doc.text(text, x, y);
        }
    };

    // Helper to draw color swatch
    const drawColorSwatch = (x: number, y: number, width: number, height: number, color: string, label: string) => {
        const hex = color.replace('#', '');
        const r = parseInt(hex.substring(0, 2), 16);
        const g = parseInt(hex.substring(2, 4), 16);
        const b = parseInt(hex.substring(4, 6), 16);

        doc.setFillColor(r, g, b);
        doc.roundedRect(x, y, width, height, 3, 3, 'F');

        addText(label, x, y + height + 6, { fontSize: 8, fontStyle: 'bold' });
        addText(color.toUpperCase(), x, y + height + 12, { fontSize: 7, color: '#666666' });
    };

    // ========== PAGE 1: COVER ==========
    {
        // Background gradient (simplified as solid color for PDF)
        const hex = colors.primary.replace('#', '');
        const r = parseInt(hex.substring(0, 2), 16);
        const g = parseInt(hex.substring(2, 4), 16);
        const b = parseInt(hex.substring(4, 6), 16);
        doc.setFillColor(r, g, b);
        doc.rect(0, 0, pageWidth, pageHeight, 'F');

        // Brand name (centered, white)
        addText(brand.name.toUpperCase(), pageWidth / 2 - 30, pageHeight / 2, {
            fontSize: 36,
            fontStyle: 'bold',
            color: '#FFFFFF'
        });

        // Subtitle (use vibe or strategy mission)
        const subtitle = brand.strategy?.mission || `${brand.vibe} brand identity`;
        addText(subtitle.substring(0, 60), pageWidth / 2 - 40, pageHeight / 2 + 15, {
            fontSize: 14,
            color: '#FFFFFF'
        });

        // Footer
        addText('Brand Guidelines', pageWidth / 2 - 20, pageHeight - 30, { fontSize: 10, color: '#FFFFFF' });
        addText('Generated by Glyph', pageWidth / 2 - 22, pageHeight - 20, { fontSize: 8, color: '#FFFFFF' });
    }

    // ========== PAGE 2: LOGO USAGE ==========
    doc.addPage();
    {
        addText('Logo', margin, 30, { fontSize: 28, fontStyle: 'bold' });
        addText('Usage Guidelines', margin, 40, { fontSize: 14, color: '#666666' });

        // Logo description
        addText(
            `The ${brand.name} logo is the primary visual identifier of the brand. ` +
            `Always maintain minimum clear space around the logo equal to the height of the icon.`,
            margin, 60, { fontSize: 10, maxWidth: contentWidth }
        );

        // Logo shape info
        addText('Primary Shape', margin, 85, { fontSize: 12, fontStyle: 'bold' });
        addText(`Shape: ${brand.shape.name}`, margin, 95, { fontSize: 10, color: '#666666' });
        addText(`ViewBox: ${brand.shape.viewBox || '0 0 24 24'}`, margin, 103, { fontSize: 10, color: '#666666' });

        // Usage rules
        addText('Do\'s', margin, 130, { fontSize: 12, fontStyle: 'bold', color: '#22c55e' });
        addText('• Use the provided SVG files for all digital applications', margin, 140, { fontSize: 9 });
        addText('• Maintain aspect ratio when scaling', margin, 148, { fontSize: 9 });
        addText('• Use logo-white.svg on dark backgrounds', margin, 156, { fontSize: 9 });

        addText('Don\'ts', margin, 175, { fontSize: 12, fontStyle: 'bold', color: '#ef4444' });
        addText('• Do not stretch or distort the logo', margin, 185, { fontSize: 9 });
        addText('• Do not change the logo colors arbitrarily', margin, 193, { fontSize: 9 });
        addText('• Do not add effects like shadows or gradients', margin, 201, { fontSize: 9 });
    }

    // ========== PAGE 3: COLOR PALETTE ==========
    doc.addPage();
    {
        addText('Color Palette', margin, 30, { fontSize: 28, fontStyle: 'bold' });
        addText('Brand Colors', margin, 40, { fontSize: 14, color: '#666666' });

        const swatchSize = 35;
        let swatchX = margin;
        const swatchY = 60;

        // Primary
        drawColorSwatch(swatchX, swatchY, swatchSize, swatchSize, colors.primary, 'Primary');
        swatchX += swatchSize + 15;

        // Accent
        if (colors.accent) {
            drawColorSwatch(swatchX, swatchY, swatchSize, swatchSize, colors.accent, 'Accent');
            swatchX += swatchSize + 15;
        }

        // Surface
        drawColorSwatch(swatchX, swatchY, swatchSize, swatchSize, colors.surface, 'Surface');
        swatchX += swatchSize + 15;

        // Background
        drawColorSwatch(swatchX, swatchY, swatchSize, swatchSize, colors.bg, 'Background');

        // Text color
        drawColorSwatch(margin, swatchY + 70, swatchSize, swatchSize, colors.text, 'Text');

        // Usage notes
        addText('Color Usage', margin, 175, { fontSize: 12, fontStyle: 'bold' });
        addText(
            'Primary: Main brand color for CTAs, headers, and key UI elements.',
            margin, 188, { fontSize: 9, maxWidth: contentWidth }
        );
        addText(
            'Surface: Card backgrounds and elevated elements.',
            margin, 200, { fontSize: 9, maxWidth: contentWidth }
        );
        addText(
            'Background: Page and section backgrounds.',
            margin, 212, { fontSize: 9, maxWidth: contentWidth }
        );
    }

    // ========== PAGE 4: TYPOGRAPHY ==========
    doc.addPage();
    {
        addText('Typography', margin, 30, { fontSize: 28, fontStyle: 'bold' });
        addText('Font System', margin, 40, { fontSize: 14, color: '#666666' });

        // Primary font
        addText('Primary Typeface', margin, 65, { fontSize: 12, fontStyle: 'bold' });
        addText(brand.font.name, margin, 78, { fontSize: 24, fontStyle: 'bold' });
        addText(brand.font.heading || brand.font.name, margin, 90, { fontSize: 10, color: '#666666' });

        // Type scale
        addText('Type Scale', margin, 115, { fontSize: 12, fontStyle: 'bold' });

        const typeScale = [
            { name: 'H1 / Display', size: 48, weight: '700' },
            { name: 'H2 / Title', size: 32, weight: '600' },
            { name: 'H3 / Heading', size: 24, weight: '600' },
            { name: 'Body', size: 16, weight: '400' },
            { name: 'Caption', size: 12, weight: '400' },
        ];

        let typeY = 128;
        typeScale.forEach(item => {
            addText(item.name, margin, typeY, { fontSize: 9, color: '#666666' });
            addText(`${item.size}px / ${item.weight}`, margin + 60, typeY, { fontSize: 9 });
            typeY += 12;
        });

        // Font loading
        addText('Implementation', margin, 200, { fontSize: 12, fontStyle: 'bold' });
        addText(
            `Load ${brand.font.name} from Google Fonts or self-host the font files.`,
            margin, 213, { fontSize: 9, maxWidth: contentWidth }
        );
    }

    // Return as blob
    return doc.output('blob');
}

/**
 * Download brand book as PDF
 */
export async function downloadBrandBookPDF(brand: BrandIdentity): Promise<void> {
    const blob = await generateBrandBookPDF(brand);
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${brand.name.toLowerCase().replace(/\s+/g, '-')}-brand-guidelines.pdf`;
    link.click();
    URL.revokeObjectURL(url);
}
