import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import { BrandIdentity } from '@/lib/data';
import { generateSimpleLogoSVG } from '@/components/export/ExportSVG';
import {
  getStoredLogoSVG,
  generateStoredWordmarkSVG,
  generateStoredFaviconSVG,
  generateDarkLightVariants
} from '@/components/logo-engine/renderers/stored-logo-export';

export async function exportBrandPackage(brand: BrandIdentity) {
  const zip = new JSZip();
  const folderName = brand.name.toLowerCase().replace(/\s+/g, '-');
  const root = zip.folder(folderName);

  if (!root) {
    console.error("Failed to create zip folder");
    return;
  }

  // 1. ICONS / LOGOS - Both composed (visual) and simple (shape-only) versions
  const icons = root.folder("icons");
  if (icons) {
    // Composed logos (EXACT match to preview - uses stored SVG)
    icons.file("logo-composed-color.svg", getStoredLogoSVG(brand, 'color'));
    icons.file("logo-composed-black.svg", getStoredLogoSVG(brand, 'black'));
    icons.file("logo-composed-white.svg", getStoredLogoSVG(brand, 'white'));

    // Dark mode variant (auto-adjusted for dark backgrounds)
    const { dark: darkVariant } = generateDarkLightVariants(brand);
    icons.file("logo-dark-mode.svg", darkVariant);

    // Simple shape-only logos (clean vector of just the shape)
    icons.file("logo-simple-color.svg", generateSimpleLogoSVG(brand, 'color'));
    icons.file("logo-simple-black.svg", generateSimpleLogoSVG(brand, 'black'));
    icons.file("logo-simple-white.svg", generateSimpleLogoSVG(brand, 'white'));

    // Wordmark (logo + brand name) - uses stored logo
    icons.file("wordmark-color.svg", generateStoredWordmarkSVG(brand, 'color'));
    icons.file("wordmark-black.svg", generateStoredWordmarkSVG(brand, 'black'));
    icons.file("wordmark-white.svg", generateStoredWordmarkSVG(brand, 'white'));

    // Favicon - uses stored logo
    icons.file("favicon.svg", generateStoredFaviconSVG(brand));
  }

  // 2. TOKENS / CODE
  const tokens = root.folder("tokens");
  if (tokens) {
    // A. theme.json
    tokens.file("theme.json", JSON.stringify(brand.theme, null, 2));

    // B. tailwind.config.js
    const tailwindConfig = `/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        brand: {
          50: '${brand.theme.tokens.light.bg}',
          100: '${brand.theme.tokens.light.surface}',
          500: '${brand.theme.tokens.light.primary}',
          900: '${brand.theme.tokens.light.text}',
        }
      },
      fontFamily: {
        sans: ['${brand.font.name}', 'sans-serif'],
      }
    },
  },
}`;
    tokens.file("tailwind.config.js", tailwindConfig);

    // C. css-variables.css
    const cssVars = `:root {
  --brand-primary: ${brand.theme.tokens.light.primary};
  --brand-bg: ${brand.theme.tokens.light.bg};
  --brand-surface: ${brand.theme.tokens.light.surface};
  --brand-text: ${brand.theme.tokens.light.text};
  --font-heading: '${brand.font.name}';
  --font-body: '${brand.font.name}';
}`;
    tokens.file("variables.css", cssVars);
  }

  // 3. README
  const readme = `
# ${brand.name} Brand Identity
Generated by Glyph (https://glyph.software)

## Contents
- /icons: SVG vector logo files
- /tokens: Development tokens for Tailwind CSS and CSS variables

## Logo Files

### Composed Logos (RECOMMENDED)
These match exactly what you see in the app - the full visual composition:
- logo-composed-color.svg - Primary brand color
- logo-composed-black.svg - Monotone black
- logo-composed-white.svg - For dark backgrounds

### Simple Logos
Clean vector of just the brand shape:
- logo-simple-color.svg - Primary color
- logo-simple-black.svg - Monotone black  
- logo-simple-white.svg - For dark backgrounds

### Wordmarks
Logo with brand name text:
- wordmark-color.svg
- wordmark-black.svg

### Favicon
- favicon.svg - Optimized for browser tabs

## Usage
- Use 'logo-composed-color.svg' for most applications
- Use white variants on dark backgrounds
- Always maintain clear space around the logo

## Fonts
Primary Font: ${brand.font.name}
This brand uses Google Fonts. You may need to license them for offline use.
`;
  root.file("README.txt", readme.trim());

  // GENERATE ZIP
  const content = await zip.generateAsync({ type: "blob" });
  saveAs(content, `${folderName}-assets.zip`);
}
