/**
 * PDF Generator for Brand Guidelines
 *
 * Uses jspdf to create comprehensive 15+ page brand guideline PDFs.
 * Includes logo usage, clear space rules, "don't do this" examples,
 * color palette, typography, and application examples.
 */

import { jsPDF } from 'jspdf';
import { BrandIdentity } from '@/lib/data';
import { getStoredLogoSVG } from '@/components/logo-engine/renderers/stored-logo-export';

/**
 * Generate a comprehensive brand guidelines PDF (15+ pages)
 */
export async function generateBrandBookPDF(brand: BrandIdentity): Promise<Blob> {
    const colors = brand.theme.tokens.light;
    const darkColors = brand.theme.tokens.dark;
    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const contentWidth = pageWidth - (margin * 2);

    // Helper functions
    const hexToRgb = (hex: string) => {
        const cleanHex = hex.replace('#', '');
        return {
            r: parseInt(cleanHex.substring(0, 2), 16),
            g: parseInt(cleanHex.substring(2, 4), 16),
            b: parseInt(cleanHex.substring(4, 6), 16)
        };
    };

    const addText = (text: string, x: number, y: number, options?: {
        fontSize?: number;
        fontStyle?: 'normal' | 'bold';
        color?: string;
        maxWidth?: number;
        align?: 'left' | 'center' | 'right';
    }) => {
        const { fontSize = 12, fontStyle = 'normal', color = '#1a1a1a', maxWidth, align = 'left' } = options || {};
        doc.setFontSize(fontSize);
        doc.setFont('helvetica', fontStyle);
        const { r, g, b } = hexToRgb(color);
        doc.setTextColor(r, g, b);

        if (maxWidth) {
            doc.text(text, x, y, { maxWidth, align });
        } else {
            doc.text(text, x, y, { align });
        }
    };

    const drawRect = (x: number, y: number, w: number, h: number, color: string, radius = 0) => {
        const { r, g, b } = hexToRgb(color);
        doc.setFillColor(r, g, b);
        if (radius > 0) {
            doc.roundedRect(x, y, w, h, radius, radius, 'F');
        } else {
            doc.rect(x, y, w, h, 'F');
        }
    };

    const drawColorSwatch = (x: number, y: number, width: number, height: number, color: string, label: string, showHex = true) => {
        drawRect(x, y, width, height, color, 3);
        addText(label, x, y + height + 6, { fontSize: 8, fontStyle: 'bold' });
        if (showHex) {
            addText(color.toUpperCase(), x, y + height + 12, { fontSize: 7, color: '#666666' });
        }
    };

    const addPageNumber = (pageNum: number) => {
        addText(`${pageNum}`, pageWidth - margin, pageHeight - 10, { fontSize: 8, color: '#999999' });
    };

    const addSectionHeader = (title: string, subtitle: string, y = 30) => {
        addText(title, margin, y, { fontSize: 28, fontStyle: 'bold' });
        addText(subtitle, margin, y + 12, { fontSize: 12, color: '#666666' });
        return y + 30;
    };

    let pageNum = 1;

    // ========== PAGE 1: COVER ==========
    {
        const { r, g, b } = hexToRgb(colors.primary);
        doc.setFillColor(r, g, b);
        doc.rect(0, 0, pageWidth, pageHeight, 'F');

        addText(brand.name.toUpperCase(), pageWidth / 2, pageHeight / 2 - 10, {
            fontSize: 42,
            fontStyle: 'bold',
            color: '#FFFFFF',
            align: 'center'
        });

        const subtitle = brand.strategy?.tagline || `${brand.vibe} brand identity`;
        addText(subtitle, pageWidth / 2, pageHeight / 2 + 8, {
            fontSize: 14,
            color: '#FFFFFF',
            align: 'center',
            maxWidth: contentWidth
        });

        addText('BRAND GUIDELINES', pageWidth / 2, pageHeight - 40, {
            fontSize: 10,
            color: '#FFFFFF',
            align: 'center'
        });
        addText(`Generated by Glyph • ${new Date().getFullYear()}`, pageWidth / 2, pageHeight - 30, {
            fontSize: 8,
            color: '#FFFFFF',
            align: 'center'
        });
    }

    // ========== PAGE 2: TABLE OF CONTENTS ==========
    doc.addPage();
    pageNum++;
    {
        addSectionHeader('Contents', 'Brand Guidelines Overview');

        const tocItems = [
            { page: 3, title: 'Brand Overview' },
            { page: 4, title: 'Logo - Primary Mark' },
            { page: 5, title: 'Logo - Color Variations' },
            { page: 6, title: 'Logo - Clear Space Rules' },
            { page: 7, title: 'Logo - Minimum Sizes' },
            { page: 8, title: 'Logo - Don\'ts' },
            { page: 9, title: 'Color Palette - Primary' },
            { page: 10, title: 'Color Palette - Extended' },
            { page: 11, title: 'Typography - Headings' },
            { page: 12, title: 'Typography - Body & Hierarchy' },
            { page: 13, title: 'Typography - Don\'ts' },
            { page: 14, title: 'Iconography & Graphics' },
            { page: 15, title: 'Application Examples' },
            { page: 16, title: 'Digital Assets & Contact' },
        ];

        let tocY = 70;
        tocItems.forEach(item => {
            addText(item.title, margin, tocY, { fontSize: 11 });
            addText(`${item.page}`, pageWidth - margin, tocY, { fontSize: 11, color: '#666666', align: 'right' });

            // Dotted line
            doc.setDrawColor(200, 200, 200);
            doc.setLineDashPattern([1, 2], 0);
            doc.line(margin + 80, tocY - 1, pageWidth - margin - 15, tocY - 1);
            doc.setLineDashPattern([], 0);

            tocY += 12;
        });

        addPageNumber(pageNum);
    }

    // ========== PAGE 3: BRAND OVERVIEW ==========
    doc.addPage();
    pageNum++;
    {
        addSectionHeader('Brand Overview', 'Who We Are');

        let y = 70;

        if (brand.strategy?.mission) {
            addText('Mission', margin, y, { fontSize: 12, fontStyle: 'bold' });
            addText(brand.strategy.mission, margin, y + 10, { fontSize: 10, maxWidth: contentWidth });
            y += 35;
        }

        if (brand.strategy?.vision) {
            addText('Vision', margin, y, { fontSize: 12, fontStyle: 'bold' });
            addText(brand.strategy.vision, margin, y + 10, { fontSize: 10, maxWidth: contentWidth });
            y += 35;
        }

        if (brand.strategy?.values && brand.strategy.values.length > 0) {
            addText('Core Values', margin, y, { fontSize: 12, fontStyle: 'bold' });
            y += 12;
            brand.strategy.values.forEach((value, i) => {
                addText(`• ${value}`, margin + 5, y, { fontSize: 10 });
                y += 8;
            });
            y += 10;
        }

        if (brand.strategy?.archetype) {
            addText('Brand Archetype', margin, y, { fontSize: 12, fontStyle: 'bold' });
            addText(brand.strategy.archetype, margin, y + 10, { fontSize: 10, color: colors.primary });
            y += 30;
        }

        if (brand.strategy?.voice) {
            addText('Brand Voice', margin, y, { fontSize: 12, fontStyle: 'bold' });
            addText(`Tone: ${brand.strategy.voice.tone}`, margin, y + 12, { fontSize: 10 });
        }

        addPageNumber(pageNum);
    }

    // ========== PAGE 4: LOGO - PRIMARY MARK ==========
    doc.addPage();
    pageNum++;
    {
        addSectionHeader('Logo', 'Primary Mark');

        addText(
            `The ${brand.name} logo is the primary visual identifier of the brand. ` +
            `It represents our values and should be treated with care in all applications.`,
            margin, 70, { fontSize: 10, maxWidth: contentWidth }
        );

        // Logo placeholder (actual logo would need SVG rendering)
        drawRect(margin, 90, contentWidth, 80, '#F5F5F5', 4);
        addText('[ Logo Preview ]', pageWidth / 2, 135, {
            fontSize: 14,
            color: '#999999',
            align: 'center'
        });

        addText('Logo Construction', margin, 190, { fontSize: 12, fontStyle: 'bold' });
        addText(
            'The logo is constructed using precise geometric principles to ensure ' +
            'visual harmony and balance across all applications.',
            margin, 202, { fontSize: 10, maxWidth: contentWidth }
        );

        addText('Algorithm:', margin, 225, { fontSize: 10, fontStyle: 'bold' });
        const algorithm = brand.generatedLogos?.[0]?.algorithm || 'Custom';
        addText(algorithm.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase()), margin + 30, 225, { fontSize: 10, color: '#666666' });

        addPageNumber(pageNum);
    }

    // ========== PAGE 5: LOGO - COLOR VARIATIONS ==========
    doc.addPage();
    pageNum++;
    {
        addSectionHeader('Logo', 'Color Variations');

        addText(
            'The logo is available in multiple color variations for different contexts and backgrounds.',
            margin, 70, { fontSize: 10, maxWidth: contentWidth }
        );

        // Full Color
        addText('Full Color (Primary)', margin, 95, { fontSize: 11, fontStyle: 'bold' });
        drawRect(margin, 105, 70, 50, '#F5F5F5', 3);
        addText('Use on light backgrounds', margin, 165, { fontSize: 9, color: '#666666' });

        // Single Color
        addText('Single Color', margin + 90, 95, { fontSize: 11, fontStyle: 'bold' });
        drawRect(margin + 90, 105, 70, 50, '#F5F5F5', 3);
        addText('Use for print/embroidery', margin + 90, 165, { fontSize: 9, color: '#666666' });

        // Reversed
        addText('Reversed (White)', margin, 185, { fontSize: 11, fontStyle: 'bold' });
        drawRect(margin, 195, 70, 50, colors.primary, 3);
        addText('Use on dark/brand color backgrounds', margin, 255, { fontSize: 9, color: '#666666' });

        // Dark Mode
        addText('Dark Mode', margin + 90, 185, { fontSize: 11, fontStyle: 'bold' });
        drawRect(margin + 90, 195, 70, 50, darkColors?.bg || '#1a1a1a', 3);
        addText('Optimized for dark interfaces', margin + 90, 255, { fontSize: 9, color: '#666666' });

        addPageNumber(pageNum);
    }

    // ========== PAGE 6: LOGO - CLEAR SPACE RULES ==========
    doc.addPage();
    pageNum++;
    {
        addSectionHeader('Logo', 'Clear Space Rules');

        addText(
            'Maintain a minimum clear space around the logo to ensure visual impact and legibility. ' +
            'The clear space is defined as "X" where X equals the height of the logo icon.',
            margin, 70, { fontSize: 10, maxWidth: contentWidth }
        );

        // Clear space diagram
        drawRect(margin + 30, 100, 110, 80, '#E8F4FF', 0);
        drawRect(margin + 50, 115, 70, 50, '#F5F5F5', 3);

        // X markers
        addText('X', margin + 35, 115, { fontSize: 8, color: colors.primary });
        addText('X', margin + 35, 145, { fontSize: 8, color: colors.primary });
        addText('X', margin + 125, 140, { fontSize: 8, color: colors.primary });
        addText('X', margin + 85, 105, { fontSize: 8, color: colors.primary });

        addText('Clear Space Diagram', margin + 50, 195, { fontSize: 10, fontStyle: 'bold' });
        addText('The blue area represents the minimum clear space required.', margin, 210, { fontSize: 9, color: '#666666' });

        addText('Rules:', margin, 235, { fontSize: 11, fontStyle: 'bold' });
        addText('• No text, graphics, or other elements within the clear space', margin, 248, { fontSize: 9 });
        addText('• Clear space scales proportionally with logo size', margin, 258, { fontSize: 9 });
        addText('• When in doubt, add more space', margin, 268, { fontSize: 9 });

        addPageNumber(pageNum);
    }

    // ========== PAGE 7: LOGO - MINIMUM SIZES ==========
    doc.addPage();
    pageNum++;
    {
        addSectionHeader('Logo', 'Minimum Sizes');

        addText(
            'To maintain legibility and visual quality, never use the logo smaller than these minimum sizes.',
            margin, 70, { fontSize: 10, maxWidth: contentWidth }
        );

        // Digital minimum
        addText('Digital Applications', margin, 100, { fontSize: 11, fontStyle: 'bold' });
        drawRect(margin, 110, 24, 24, '#F5F5F5', 2);
        addText('24px', margin + 30, 125, { fontSize: 10 });
        addText('Minimum for favicon/small icons', margin + 30, 135, { fontSize: 9, color: '#666666' });

        drawRect(margin, 150, 32, 32, '#F5F5F5', 2);
        addText('32px', margin + 40, 170, { fontSize: 10 });
        addText('Minimum for UI elements', margin + 40, 180, { fontSize: 9, color: '#666666' });

        // Print minimum
        addText('Print Applications', margin, 210, { fontSize: 11, fontStyle: 'bold' });
        addText('Minimum width: 15mm (0.6 inches)', margin, 225, { fontSize: 10 });
        addText('For business cards, letterheads, and small print materials', margin, 237, { fontSize: 9, color: '#666666' });

        addText('Large Format', margin, 260, { fontSize: 11, fontStyle: 'bold' });
        addText('No maximum size limit. Logo is vector-based and scales infinitely.', margin, 273, { fontSize: 10 });

        addPageNumber(pageNum);
    }

    // ========== PAGE 8: LOGO - DON'TS ==========
    doc.addPage();
    pageNum++;
    {
        addSectionHeader('Logo', 'Don\'ts');

        addText(
            'To maintain brand consistency, avoid these common mistakes when using the logo.',
            margin, 70, { fontSize: 10, maxWidth: contentWidth }
        );

        const donts = [
            { title: 'Don\'t stretch or distort', desc: 'Always maintain the original aspect ratio' },
            { title: 'Don\'t rotate', desc: 'Keep the logo in its original orientation' },
            { title: 'Don\'t change colors', desc: 'Only use approved color variations' },
            { title: 'Don\'t add effects', desc: 'No shadows, glows, or gradients' },
            { title: 'Don\'t outline', desc: 'Never use outlined versions' },
            { title: 'Don\'t crop', desc: 'Always show the complete logo' },
            { title: 'Don\'t use on busy backgrounds', desc: 'Ensure sufficient contrast' },
            { title: 'Don\'t recreate', desc: 'Always use official logo files' },
        ];

        let y = 95;
        let col = 0;
        donts.forEach((item, i) => {
            const x = margin + (col * 90);
            drawRect(x, y, 75, 45, '#FEE2E2', 2);

            // X mark
            doc.setDrawColor(239, 68, 68);
            doc.setLineWidth(0.5);
            doc.line(x + 60, y + 5, x + 70, y + 15);
            doc.line(x + 70, y + 5, x + 60, y + 15);

            addText(item.title, x + 3, y + 55, { fontSize: 8, fontStyle: 'bold', color: '#DC2626' });
            addText(item.desc, x + 3, y + 62, { fontSize: 7, color: '#666666', maxWidth: 72 });

            col++;
            if (col >= 2) {
                col = 0;
                y += 80;
            }
        });

        addPageNumber(pageNum);
    }

    // ========== PAGE 9: COLOR PALETTE - PRIMARY ==========
    doc.addPage();
    pageNum++;
    {
        addSectionHeader('Color Palette', 'Primary Colors');

        addText(
            'These are the core colors that define the brand identity. Use them consistently across all touchpoints.',
            margin, 70, { fontSize: 10, maxWidth: contentWidth }
        );

        // Primary color (large swatch)
        drawRect(margin, 90, contentWidth, 60, colors.primary, 4);
        addText('PRIMARY', margin + 10, 105, { fontSize: 10, fontStyle: 'bold', color: '#FFFFFF' });
        addText(colors.primary.toUpperCase(), margin + 10, 140, { fontSize: 12, color: '#FFFFFF' });

        // Secondary colors
        const swatchY = 170;
        const swatchSize = 40;

        if (colors.accent) {
            drawColorSwatch(margin, swatchY, swatchSize, swatchSize, colors.accent, 'Accent');
        }
        drawColorSwatch(margin + 55, swatchY, swatchSize, swatchSize, colors.surface, 'Surface');
        drawColorSwatch(margin + 110, swatchY, swatchSize, swatchSize, colors.bg, 'Background');

        // Text colors
        addText('Text Colors', margin, 240, { fontSize: 11, fontStyle: 'bold' });
        drawColorSwatch(margin, 252, 30, 30, colors.text, 'Primary');
        drawColorSwatch(margin + 45, 252, 30, 30, colors.muted || '#666666', 'Muted');

        addPageNumber(pageNum);
    }

    // ========== PAGE 10: COLOR PALETTE - EXTENDED ==========
    doc.addPage();
    pageNum++;
    {
        addSectionHeader('Color Palette', 'Dark Mode & Extended');

        addText('Dark Mode Colors', margin, 70, { fontSize: 11, fontStyle: 'bold' });
        addText('Optimized colors for dark interfaces and backgrounds.', margin, 82, { fontSize: 10, color: '#666666' });

        // Dark mode swatches
        const darkSwatchY = 95;
        drawColorSwatch(margin, darkSwatchY, 35, 35, darkColors?.primary || colors.primary, 'Primary');
        drawColorSwatch(margin + 50, darkSwatchY, 35, 35, darkColors?.bg || '#1a1a1a', 'Background');
        drawColorSwatch(margin + 100, darkSwatchY, 35, 35, darkColors?.surface || '#262626', 'Surface');
        drawColorSwatch(margin + 150, darkSwatchY, 35, 35, darkColors?.text || '#FFFFFF', 'Text');

        // Color usage
        addText('Color Usage Guidelines', margin, 165, { fontSize: 11, fontStyle: 'bold' });

        const usages = [
            { color: 'Primary', use: 'CTAs, links, key UI elements, brand moments' },
            { color: 'Accent', use: 'Highlights, notifications, secondary actions' },
            { color: 'Surface', use: 'Cards, modals, elevated containers' },
            { color: 'Background', use: 'Page backgrounds, large areas' },
            { color: 'Text', use: 'Body copy, headings, labels' },
        ];

        let usageY = 180;
        usages.forEach(item => {
            addText(item.color + ':', margin, usageY, { fontSize: 9, fontStyle: 'bold' });
            addText(item.use, margin + 30, usageY, { fontSize: 9, color: '#666666' });
            usageY += 12;
        });

        // Contrast requirements
        addText('Accessibility', margin, 250, { fontSize: 11, fontStyle: 'bold' });
        addText('Ensure minimum 4.5:1 contrast ratio for body text and 3:1 for large text (WCAG AA).', margin, 263, { fontSize: 9, maxWidth: contentWidth });

        addPageNumber(pageNum);
    }

    // ========== PAGE 11: TYPOGRAPHY - HEADINGS ==========
    doc.addPage();
    pageNum++;
    {
        addSectionHeader('Typography', 'Heading Styles');

        addText('Primary Typeface', margin, 70, { fontSize: 11, fontStyle: 'bold' });
        addText(brand.font.headingName || brand.font.name, margin, 85, { fontSize: 24, fontStyle: 'bold' });
        addText('Used for headlines, titles, and display text', margin, 98, { fontSize: 9, color: '#666666' });

        // Type scale
        addText('Heading Scale', margin, 125, { fontSize: 11, fontStyle: 'bold' });

        const headings = [
            { name: 'Display', size: 48, weight: 'Bold', use: 'Hero sections, landing pages' },
            { name: 'H1', size: 36, weight: 'Bold', use: 'Page titles' },
            { name: 'H2', size: 28, weight: 'Semibold', use: 'Section headers' },
            { name: 'H3', size: 22, weight: 'Semibold', use: 'Subsection headers' },
            { name: 'H4', size: 18, weight: 'Medium', use: 'Card titles, labels' },
        ];

        let headingY = 140;
        headings.forEach(h => {
            addText(h.name, margin, headingY, { fontSize: h.size > 30 ? 14 : 11, fontStyle: 'bold' });
            addText(`${h.size}px • ${h.weight}`, margin + 35, headingY, { fontSize: 9, color: '#666666' });
            addText(h.use, margin + 90, headingY, { fontSize: 9, color: '#999999' });
            headingY += 20;
        });

        addPageNumber(pageNum);
    }

    // ========== PAGE 12: TYPOGRAPHY - BODY ==========
    doc.addPage();
    pageNum++;
    {
        addSectionHeader('Typography', 'Body & Hierarchy');

        addText('Body Typeface', margin, 70, { fontSize: 11, fontStyle: 'bold' });
        addText(brand.font.bodyName || brand.font.name, margin, 85, { fontSize: 16 });
        addText('Used for body copy, paragraphs, and UI text', margin, 98, { fontSize: 9, color: '#666666' });

        // Body scale
        addText('Body Text Scale', margin, 120, { fontSize: 11, fontStyle: 'bold' });

        const bodyStyles = [
            { name: 'Body Large', size: 18, lineHeight: '28px', use: 'Introductions, featured content' },
            { name: 'Body', size: 16, lineHeight: '24px', use: 'Default paragraph text' },
            { name: 'Body Small', size: 14, lineHeight: '20px', use: 'Secondary information' },
            { name: 'Caption', size: 12, lineHeight: '16px', use: 'Labels, metadata, footnotes' },
            { name: 'Overline', size: 10, lineHeight: '14px', use: 'Category labels, all-caps' },
        ];

        let bodyY = 135;
        bodyStyles.forEach(s => {
            addText(s.name, margin, bodyY, { fontSize: 10, fontStyle: 'bold' });
            addText(`${s.size}px / ${s.lineHeight}`, margin + 40, bodyY, { fontSize: 9, color: '#666666' });
            addText(s.use, margin + 90, bodyY, { fontSize: 9, color: '#999999' });
            bodyY += 15;
        });

        // Spacing
        addText('Spacing & Rhythm', margin, 220, { fontSize: 11, fontStyle: 'bold' });
        addText('Use consistent spacing based on 4px grid. Common values: 4, 8, 12, 16, 24, 32, 48, 64px', margin, 235, { fontSize: 9, maxWidth: contentWidth });

        addText('Line Length', margin, 255, { fontSize: 11, fontStyle: 'bold' });
        addText('Optimal line length: 45-75 characters for body text to ensure readability.', margin, 268, { fontSize: 9, maxWidth: contentWidth });

        addPageNumber(pageNum);
    }

    // ========== PAGE 13: TYPOGRAPHY - DON'TS ==========
    doc.addPage();
    pageNum++;
    {
        addSectionHeader('Typography', 'Don\'ts');

        addText(
            'Avoid these common typography mistakes to maintain brand consistency.',
            margin, 70, { fontSize: 10, maxWidth: contentWidth }
        );

        const typoDonts = [
            { title: 'Don\'t use unauthorized fonts', desc: 'Stick to the brand typefaces only' },
            { title: 'Don\'t stretch text', desc: 'Never horizontally or vertically scale type' },
            { title: 'Don\'t use low contrast', desc: 'Maintain WCAG accessibility standards' },
            { title: 'Don\'t mix too many sizes', desc: 'Use the defined type scale' },
            { title: 'Don\'t center long paragraphs', desc: 'Left-align body text for readability' },
            { title: 'Don\'t use ALL CAPS for body', desc: 'Reserve caps for overlines/labels only' },
        ];

        let y = 95;
        typoDonts.forEach((item, i) => {
            drawRect(margin, y, contentWidth, 25, '#FEE2E2', 2);
            addText('✗ ' + item.title, margin + 5, y + 10, { fontSize: 9, fontStyle: 'bold', color: '#DC2626' });
            addText(item.desc, margin + 5, y + 19, { fontSize: 8, color: '#666666' });
            y += 32;
        });

        addPageNumber(pageNum);
    }

    // ========== PAGE 14: ICONOGRAPHY ==========
    doc.addPage();
    pageNum++;
    {
        addSectionHeader('Iconography', 'Graphics & Patterns');

        addText('Icon Style', margin, 70, { fontSize: 11, fontStyle: 'bold' });
        addText(
            'Use consistent icon styles that match the brand aesthetic. ' +
            'Prefer outline icons at 24px default size with 1.5-2px stroke.',
            margin, 82, { fontSize: 10, maxWidth: contentWidth }
        );

        // Icon guidelines
        addText('Icon Guidelines', margin, 110, { fontSize: 11, fontStyle: 'bold' });
        const iconRules = [
            '• Use 24x24px as the default icon size',
            '• Maintain consistent stroke width (1.5-2px)',
            '• Use brand primary color or neutral gray',
            '• Ensure icons are optically centered',
            '• Keep icons simple and recognizable',
        ];
        let iconY = 125;
        iconRules.forEach(rule => {
            addText(rule, margin, iconY, { fontSize: 9 });
            iconY += 10;
        });

        // Patterns
        addText('Graphic Elements', margin, 185, { fontSize: 11, fontStyle: 'bold' });
        addText(
            'Brand patterns and graphic elements should complement the logo. ' +
            'Use geometric shapes derived from the logo construction.',
            margin, 197, { fontSize: 10, maxWidth: contentWidth }
        );

        // Photography
        addText('Photography Style', margin, 225, { fontSize: 11, fontStyle: 'bold' });
        addText(
            'Select imagery that reflects brand values: ' +
            `${brand.vibe} aesthetic with balanced composition and authentic subjects.`,
            margin, 237, { fontSize: 10, maxWidth: contentWidth }
        );

        addPageNumber(pageNum);
    }

    // ========== PAGE 15: APPLICATION EXAMPLES ==========
    doc.addPage();
    pageNum++;
    {
        addSectionHeader('Applications', 'Usage Examples');

        addText('Business Card', margin, 70, { fontSize: 11, fontStyle: 'bold' });
        drawRect(margin, 80, 85, 50, '#F5F5F5', 3);
        addText('Standard size: 3.5" x 2"', margin, 140, { fontSize: 9, color: '#666666' });

        addText('Letterhead', margin + 100, 70, { fontSize: 11, fontStyle: 'bold' });
        drawRect(margin + 100, 80, 60, 80, '#F5F5F5', 3);
        addText('A4 / US Letter', margin + 100, 170, { fontSize: 9, color: '#666666' });

        addText('Social Media', margin, 185, { fontSize: 11, fontStyle: 'bold' });
        addText('Profile pictures, cover images, and post templates are available in the Social Media Kit.', margin, 198, { fontSize: 10, maxWidth: contentWidth });

        addText('Website', margin, 225, { fontSize: 11, fontStyle: 'bold' });
        addText('Use the logo at minimum 32px height in the header. Favicon included in the asset package.', margin, 238, { fontSize: 10, maxWidth: contentWidth });

        addText('Merchandise', margin, 260, { fontSize: 11, fontStyle: 'bold' });
        addText('For apparel and physical products, use vector files. Minimum logo size: 1 inch.', margin, 273, { fontSize: 10, maxWidth: contentWidth });

        addPageNumber(pageNum);
    }

    // ========== PAGE 16: DIGITAL ASSETS & CONTACT ==========
    doc.addPage();
    pageNum++;
    {
        addSectionHeader('Digital Assets', 'Files & Resources');

        addText('Included Assets', margin, 70, { fontSize: 11, fontStyle: 'bold' });

        const assets = [
            'logo-composed-color.svg - Full color logo',
            'logo-composed-black.svg - Single color black',
            'logo-composed-white.svg - Reversed for dark backgrounds',
            'logo-dark-mode.svg - Optimized for dark interfaces',
            'favicon.ico - Browser favicon (16, 32, 48px)',
            'apple-touch-icon.png - iOS home screen icon',
            'theme.json - Color tokens for development',
            'tailwind.config.js - Tailwind CSS configuration',
        ];

        let assetY = 85;
        assets.forEach(asset => {
            addText('• ' + asset, margin, assetY, { fontSize: 9 });
            assetY += 10;
        });

        addText('File Formats', margin, 180, { fontSize: 11, fontStyle: 'bold' });
        addText('SVG - Vector format for web and print', margin, 193, { fontSize: 9 });
        addText('PNG - Raster format at multiple sizes', margin, 203, { fontSize: 9 });
        addText('ICO - Windows favicon format', margin, 213, { fontSize: 9 });

        // Footer
        drawRect(margin, 240, contentWidth, 40, colors.primary, 4);
        addText('Generated with Glyph', margin + 10, 255, { fontSize: 10, color: '#FFFFFF' });
        addText('glyph.software', margin + 10, 268, { fontSize: 10, fontStyle: 'bold', color: '#FFFFFF' });
        addText(`© ${new Date().getFullYear()} ${brand.name}`, pageWidth - margin - 50, 260, { fontSize: 9, color: '#FFFFFF' });

        addPageNumber(pageNum);
    }

    return doc.output('blob');
}

/**
 * Download brand guidelines as PDF
 */
export async function downloadBrandBookPDF(brand: BrandIdentity): Promise<void> {
    const blob = await generateBrandBookPDF(brand);
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${brand.name.toLowerCase().replace(/\s+/g, '-')}-brand-guidelines.pdf`;
    link.click();
    URL.revokeObjectURL(url);
}
