// app/legal/terms/page.tsx
import React from 'react';

export default function TermsPage() {
    return (
        <div className="max-w-3xl mx-auto px-6 py-24 leading-relaxed text-stone-700">
            <h1 className="text-4xl font-bold mb-8 text-stone-900">Terms of Service</h1>
            <p className="mb-4 text-stone-500 text-sm">Last updated: January 2026</p>

            <div className="space-y-6">
                <section>
                    <h2 className="text-2xl font-semibold mb-4 text-stone-900">1. Introduction</h2>
                    <p>
                        Welcome to Glyph (&quot;Company&quot;, &quot;we&quot;, &quot;our&quot;, &quot;us&quot;). By accessing or using our website, services, and tools (collectively, the &quot;Services&quot;), you agree to be bound by these Terms of Service (&quot;Terms&quot;). If you do not agree to these Terms, please do not use our Services.
                    </p>
                </section>

                <section>
                    <h2 className="text-2xl font-semibold mb-4 text-stone-900">2. Use of Services</h2>
                    <p>
                        Glyph provides AI-powered brand identity generation tools. You are granted a limited, non-exclusive, non-transferable license to use our Services for your personal or commercial projects, subject to these Terms.
                    </p>
                    <ul className="list-disc list-inside mt-2 space-y-1">
                        <li>You must be at least 18 years old to use the Services.</li>
                        <li>You agree not to misuse the Services or help anyone else do so.</li>
                        <li>We reserve the right to suspend or terminate your access at any time for violations.</li>
                    </ul>
                </section>

                <section>
                    <h2 className="text-2xl font-semibold mb-4 text-stone-900">3. Intellectual Property</h2>
                    <p>
                        The content generated by Glyph (logos, color palettes, typography selections) is provided to you for your use.
                    </p>
                    <p className="mt-2">
                        <strong>Free Tier:</strong> You have a license to use generated assets for personal projects or drafting.
                    </p>
                    <p className="mt-2">
                        <strong>Pro Tier:</strong> Upon purchase/subscription, you are granted a commercial license to the specific assets exported. However, due to the nature of AI generation, we cannot guarantee exclusive trademark rights for any specific generated geometry or combination.
                    </p>
                </section>

                <section>
                    <h2 className="text-2xl font-semibold mb-4 text-stone-900">4. Disclaimer of Warranties</h2>
                    <p>
                        The Services are provided &quot;as is&quot; without warranties of any kind, either express or implied. We do not warrant that the Services will be uninterrupted or error-free.
                    </p>
                </section>

                <section>
                    <h2 className="text-2xl font-semibold mb-4 text-stone-900">5. Limitation of Liability</h2>
                    <p>
                        To the fullest extent permitted by law, Glyph shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues.
                    </p>
                </section>

                <section>
                    <h2 className="text-2xl font-semibold mb-4 text-stone-900">6. Changes to Terms</h2>
                    <p>
                        We may modify these Terms at any time. We will provide notice of significant changes by updating the date at the top of these Terms.
                    </p>
                </section>

                <section>
                    <h2 className="text-2xl font-semibold mb-4 text-stone-900">7. Contact Us</h2>
                    <p>
                        If you have any questions about these Terms, please contact us at support@glyph.com.
                    </p>
                </section>
            </div>
        </div>
    );
}
