"use client";

import React from 'react';
import { BrandIdentity } from '@/lib/data';
import { LogoComposition } from '@/components/brand/LogoComposition';
import { cn } from '@/lib/utils';

interface BrandGuidelinesProps {
    brand: BrandIdentity;
}

/**
 * BrandGuidelines - The "$500 Brand Package" in a single printable page
 * Shows Logo System, Color System, Typography System, and Usage Rules
 */
export function BrandGuidelines({ brand }: BrandGuidelinesProps) {
    const t = brand.theme.tokens;

    return (
        <div className="max-w-4xl mx-auto bg-white min-h-screen shadow-2xl border border-stone-200 print:shadow-none print:border-none">

            {/* HEADER */}
            <header className="p-12 md:p-16 border-b border-stone-100">
                <h1 className={cn("text-4xl md:text-5xl font-bold text-stone-900 mb-4", brand.font.heading)}>
                    {brand.name}
                </h1>
                <p className="text-stone-500 text-lg mb-6 max-w-lg">
                    A {brand.vibe} brand identity system
                </p>
                <div className="flex items-center gap-4 text-stone-400 font-mono text-xs uppercase tracking-widest">
                    <span>Brand Guidelines v1.0</span>
                    <span className="w-1 h-1 rounded-full bg-stone-300" />
                    <span>Generated by Glyph</span>
                </div>
            </header>

            {/* SECTION 1: LOGO CONSTRUCTION */}
            <section className="p-12 md:p-16 border-b border-stone-100">
                <div className="flex items-center gap-3 mb-8">
                    <span className="text-xs font-mono text-stone-400 bg-stone-100 px-2 py-1 rounded">01</span>
                    <h2 className="font-mono text-sm text-stone-500 uppercase tracking-widest">Logo Construction</h2>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    {/* Primary Mark - Light Background */}
                    <div className="relative p-12 bg-stone-50 rounded-2xl border border-stone-100 flex items-center justify-center aspect-[4/3]">
                        {/* Clear Space Guide */}
                        <div className="absolute inset-0 border border-dashed border-stone-200 m-8 rounded-lg opacity-60" />
                        <div className="w-32 h-32">
                            <LogoComposition brand={brand} />
                        </div>
                        <span className="absolute bottom-3 left-3 text-[10px] text-stone-400 font-mono uppercase">Primary Mark</span>
                        <span className="absolute bottom-3 right-3 text-[10px] text-stone-300 font-mono">Light BG</span>
                    </div>

                    {/* Symbol - Dark Background */}
                    <div className="relative p-12 bg-stone-900 rounded-2xl border border-stone-800 flex items-center justify-center aspect-[4/3]">
                        <div className="absolute inset-0 border border-dashed border-stone-700 m-8 rounded-lg opacity-40" />
                        <div className="w-24 h-24">
                            <LogoComposition brand={brand} overrideColors={{ primary: '#FFFFFF' }} />
                        </div>
                        <span className="absolute bottom-3 left-3 text-[10px] text-stone-500 font-mono uppercase">Symbol</span>
                        <span className="absolute bottom-3 right-3 text-[10px] text-stone-600 font-mono">Dark BG</span>
                    </div>

                    {/* Monochrome - Black */}
                    <div className="relative p-8 bg-white rounded-2xl border border-stone-200 flex items-center justify-center">
                        <div className="w-20 h-20 opacity-90">
                            <LogoComposition brand={brand} overrideColors={{ primary: '#000000' }} />
                        </div>
                        <span className="absolute bottom-3 left-3 text-[10px] text-stone-400 font-mono uppercase">Monochrome</span>
                    </div>

                    {/* Wordmark */}
                    <div className="relative p-8 bg-white rounded-2xl border border-stone-200 flex items-center justify-center">
                        <h3 className={cn("text-3xl font-bold text-stone-900", brand.font.heading)}>
                            {brand.name}
                        </h3>
                        <span className="absolute bottom-3 left-3 text-[10px] text-stone-400 font-mono uppercase">Wordmark</span>
                    </div>
                </div>

                {/* Clear Space Rule */}
                <div className="mt-8 p-4 bg-stone-50 rounded-xl border border-stone-100">
                    <p className="text-sm text-stone-600">
                        <span className="font-semibold text-stone-800">Clear Space:</span> Always maintain a minimum clear space around the logo equal to the height of the lettermark. This ensures visual integrity across all applications.
                    </p>
                </div>
            </section>

            {/* SECTION 2: COLOR SYSTEM */}
            <section className="p-12 md:p-16 border-b border-stone-100">
                <div className="flex items-center gap-3 mb-8">
                    <span className="text-xs font-mono text-stone-400 bg-stone-100 px-2 py-1 rounded">02</span>
                    <h2 className="font-mono text-sm text-stone-500 uppercase tracking-widest">Color System</h2>
                </div>

                {/* Light Mode */}
                <div className="mb-8">
                    <h4 className="text-xs font-mono text-stone-400 uppercase tracking-wider mb-4 flex items-center gap-2">
                        <div className="w-3 h-3 rounded-full bg-white border border-stone-200" />
                        Light Mode
                    </h4>
                    <div className="grid grid-cols-4 gap-4">
                        <ColorSwatch label="Primary" hex={t.light.primary} />
                        <ColorSwatch label="Background" hex={t.light.bg} />
                        <ColorSwatch label="Text" hex={t.light.text} />
                        <ColorSwatch label="Border" hex={t.light.border} />
                    </div>
                </div>

                {/* Dark Mode */}
                <div>
                    <h4 className="text-xs font-mono text-stone-400 uppercase tracking-wider mb-4 flex items-center gap-2">
                        <div className="w-3 h-3 rounded-full bg-stone-800 border border-stone-600" />
                        Dark Mode
                    </h4>
                    <div className="grid grid-cols-4 gap-4">
                        <ColorSwatch label="Primary" hex={t.dark.primary} dark />
                        <ColorSwatch label="Background" hex={t.dark.bg} dark />
                        <ColorSwatch label="Text" hex={t.dark.text} dark />
                        <ColorSwatch label="Border" hex={t.dark.border} dark />
                    </div>
                </div>
            </section>

            {/* SECTION 3: TYPOGRAPHY */}
            <section className="p-12 md:p-16 border-b border-stone-100">
                <div className="flex items-center gap-3 mb-8">
                    <span className="text-xs font-mono text-stone-400 bg-stone-100 px-2 py-1 rounded">03</span>
                    <h2 className="font-mono text-sm text-stone-500 uppercase tracking-widest">Typography</h2>
                </div>

                <div className="space-y-8 border-l-2 border-stone-100 pl-8">
                    {/* Display */}
                    <div>
                        <div className="flex items-center gap-4 mb-2">
                            <span className="text-[10px] font-mono text-stone-400 bg-stone-50 px-2 py-0.5 rounded">DISPLAY</span>
                            <span className="text-[10px] font-mono text-stone-300">{brand.font.headingName || 'Inter'} • 700 • -0.04em</span>
                        </div>
                        <h1 className={cn("text-5xl font-bold text-stone-900", brand.font.heading)} style={{ letterSpacing: '-0.04em' }}>
                            The quick brown fox
                        </h1>
                    </div>

                    {/* Heading */}
                    <div>
                        <div className="flex items-center gap-4 mb-2">
                            <span className="text-[10px] font-mono text-stone-400 bg-stone-50 px-2 py-0.5 rounded">H1</span>
                            <span className="text-[10px] font-mono text-stone-300">{brand.font.headingName || 'Inter'} • 600 • -0.02em</span>
                        </div>
                        <h2 className={cn("text-3xl font-semibold text-stone-800", brand.font.heading)} style={{ letterSpacing: '-0.02em' }}>
                            Jumps over the lazy dog
                        </h2>
                    </div>

                    {/* Body */}
                    <div>
                        <div className="flex items-center gap-4 mb-2">
                            <span className="text-[10px] font-mono text-stone-400 bg-stone-50 px-2 py-0.5 rounded">BODY</span>
                            <span className="text-[10px] font-mono text-stone-300">{brand.font.bodyName || 'Inter'} • 400 • 1.6 line-height</span>
                        </div>
                        <p className={cn("text-lg text-stone-600 max-w-lg leading-relaxed", brand.font.body)}>
                            Brand identity is the visible elements of a brand, such as color, design, and logo, that identify and distinguish the brand in consumers' minds.
                        </p>
                    </div>

                    {/* Caption */}
                    <div>
                        <div className="flex items-center gap-4 mb-2">
                            <span className="text-[10px] font-mono text-stone-400 bg-stone-50 px-2 py-0.5 rounded">CAPTION</span>
                            <span className="text-[10px] font-mono text-stone-300">Mono • Uppercase • 0.1em tracking</span>
                        </div>
                        <p className="text-xs font-mono text-stone-500 uppercase tracking-widest">
                            Technical labels and metadata
                        </p>
                    </div>
                </div>
            </section>

            {/* SECTION 4: USAGE RULES */}
            <section className="p-12 md:p-16">
                <div className="flex items-center gap-3 mb-8">
                    <span className="text-xs font-mono text-stone-400 bg-stone-100 px-2 py-1 rounded">04</span>
                    <h2 className="font-mono text-sm text-stone-500 uppercase tracking-widest">Usage Rules</h2>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    {/* DO's */}
                    <div className="p-6 rounded-2xl border-2 border-green-200 bg-green-50/50">
                        <h4 className="text-sm font-bold text-green-700 uppercase tracking-wider mb-4 flex items-center gap-2">
                            <span className="w-5 h-5 rounded-full bg-green-500 text-white text-xs flex items-center justify-center">✓</span>
                            Do
                        </h4>
                        <ul className="space-y-3 text-sm text-green-800">
                            <li className="flex items-start gap-2">
                                <span className="text-green-500 mt-0.5">•</span>
                                Use the logo on high-contrast backgrounds
                            </li>
                            <li className="flex items-start gap-2">
                                <span className="text-green-500 mt-0.5">•</span>
                                Maintain minimum clear space around the mark
                            </li>
                            <li className="flex items-start gap-2">
                                <span className="text-green-500 mt-0.5">•</span>
                                Use approved color variations only
                            </li>
                            <li className="flex items-start gap-2">
                                <span className="text-green-500 mt-0.5">•</span>
                                Scale proportionally from corner handles
                            </li>
                        </ul>
                    </div>

                    {/* DON'Ts */}
                    <div className="p-6 rounded-2xl border-2 border-red-200 bg-red-50/50">
                        <h4 className="text-sm font-bold text-red-700 uppercase tracking-wider mb-4 flex items-center gap-2">
                            <span className="w-5 h-5 rounded-full bg-red-500 text-white text-xs flex items-center justify-center">✕</span>
                            Don't
                        </h4>
                        <ul className="space-y-3 text-sm text-red-800">
                            <li className="flex items-start gap-2">
                                <span className="text-red-500 mt-0.5">•</span>
                                Stretch or distort the logo
                            </li>
                            <li className="flex items-start gap-2">
                                <span className="text-red-500 mt-0.5">•</span>
                                Place on busy or low-contrast backgrounds
                            </li>
                            <li className="flex items-start gap-2">
                                <span className="text-red-500 mt-0.5">•</span>
                                Add shadows, gradients, or effects
                            </li>
                            <li className="flex items-start gap-2">
                                <span className="text-red-500 mt-0.5">•</span>
                                Rotate or crop the mark
                            </li>
                        </ul>
                    </div>
                </div>
            </section>

            {/* FOOTER */}
            <footer className="p-8 bg-stone-50 border-t border-stone-100 text-center">
                <p className="text-xs text-stone-400 font-mono">
                    {brand.name} Brand Guidelines • Generated by Glyph • {new Date().getFullYear()}
                </p>
            </footer>
        </div>
    );
}

// Helper component for color swatches
function ColorSwatch({ label, hex, dark = false }: { label: string; hex: string; dark?: boolean }) {
    return (
        <div className="space-y-2">
            <div
                className={cn(
                    "h-20 rounded-xl shadow-sm",
                    !dark && "border border-stone-200"
                )}
                style={{ backgroundColor: hex }}
            />
            <div className="flex justify-between items-center">
                <span className="text-xs font-medium text-stone-700">{label}</span>
                <span className="text-[10px] font-mono text-stone-400">{hex.toUpperCase()}</span>
            </div>
        </div>
    );
}
